// tslint:disable-next-line: max-line-length
export const COUNTRIES = [
  {tr_code: 'Afghanistan', name: 'Afghanistan', dial_code: '+93', code: 'AF' },
  {tr_code: 'AlandIslands', name: 'Aland Islands', dial_code: '+358', code: 'AX' },
  {tr_code: 'Albania', name: 'Albania', dial_code: '+355', code: 'AL' },
  {tr_code: 'Algeria', name: 'Algeria', dial_code: '+213', code: 'DZ' },
  {tr_code: 'AmericanSamoa', name: 'AmericanSamoa', dial_code: '+1684', code: 'AS' },
  {tr_code: 'Andorra', name: 'Andorra', dial_code: '+376', code: 'AD' },
  {tr_code: 'Angola', name: 'Angola', dial_code: '+244', code: 'AO' },
  {tr_code: 'Anguilla', name: 'Anguilla', dial_code: '+1264', code: 'AI' },
  {tr_code: 'Antarctica', name: 'Antarctica', dial_code: '+672', code: 'AQ' },
  {tr_code: 'AntiguaandBarbuda', name: 'Antigua and Barbuda', dial_code: '+1268', code: 'AG' },
  {tr_code: 'Argentina', name: 'Argentina', dial_code: '+54', code: 'AR' },
  {tr_code: 'Armenia', name: 'Armenia', dial_code: '+374', code: 'AM' },
  {tr_code: 'Aruba', name: 'Aruba', dial_code: '+297', code: 'AW' },
  {tr_code: 'Australia', name: 'Australia', dial_code: '+61', code: 'AU' },
  {tr_code: 'Austria', name: 'Austria', dial_code: '+43', code: 'AT' },
  {tr_code: 'Azerbaijan', name: 'Azerbaijan', dial_code: '+994', code: 'AZ' },
  {tr_code: 'Bahamas', name: 'Bahamas', dial_code: '+1242', code: 'BS' },
  {tr_code: 'Bahrain', name: 'Bahrain', dial_code: '+973', code: 'BH' },
  {tr_code: 'Bangladesh', name: 'Bangladesh', dial_code: '+880', code: 'BD' },
  {tr_code: 'Barbados', name: 'Barbados', dial_code: '+1246', code: 'BB' },
  {tr_code: 'Belarus', name: 'Belarus', dial_code: '+375', code: 'BY' },
  {tr_code: 'Belgium', name: 'Belgium', dial_code: '+32', code: 'BE' },
  {tr_code: 'Belize', name: 'Belize', dial_code: '+501', code: 'BZ' },
  {tr_code: 'Benin', name: 'Benin', dial_code: '+229', code: 'BJ' },
  {tr_code: 'Bermuda', name: 'Bermuda', dial_code: '+1441', code: 'BM' },
  {tr_code: 'Bhutan', name: 'Bhutan', dial_code: '+975', code: 'BT' },
  {tr_code: 'BoliviaPlurinationalStateofbolivia', name: 'Bolivia, Plurinational State of bolivia', dial_code: '+591', code: 'BO' },
  {tr_code: 'BosniaandHerzegovina', name: 'Bosnia and Herzegovina', dial_code: '+387', code: 'BA' },
  {tr_code: 'Botswana', name: 'Botswana', dial_code: '+267', code: 'BW' },
  {tr_code: 'Brazil', name: 'Brazil', dial_code: '+55', code: 'BR' },
  {tr_code: 'BritishIndianOceanTerritory', name: 'British Indian Ocean Territory', dial_code: '+246', code: 'IO' },
  {tr_code: 'BruneiDarussalam', name: 'Brunei Darussalam', dial_code: '+673', code: 'BN' },
  {tr_code: 'Bulgaria', name: 'Bulgaria', dial_code: '+359', code: 'BG' },
  {tr_code: 'BurkinaFaso', name: 'Burkina Faso', dial_code: '+226', code: 'BF' },
  {tr_code: 'Burundi', name: 'Burundi', dial_code: '+257', code: 'BI' },
  {tr_code: 'Cambodia', name: 'Cambodia', dial_code: '+855', code: 'KH' },
  {tr_code: 'Cameroon', name: 'Cameroon', dial_code: '+237', code: 'CM' },
  {tr_code: 'Canada', name: 'Canada', dial_code: '+1', code: 'CA' },
  {tr_code: 'CapeVerde', name: 'Cape Verde', dial_code: '+238', code: 'CV' },
  {tr_code: 'CaymanIslands', name: 'Cayman Islands', dial_code: '+ 345', code: 'KY' },
  {tr_code: 'CentralAfricanRepublic', name: 'Central African Republic', dial_code: '+236', code: 'CF' },
  {tr_code: 'Chad', name: 'Chad', dial_code: '+235', code: 'TD' },
  {tr_code: 'Chile', name: 'Chile', dial_code: '+56', code: 'CL' },
  {tr_code: 'China', name: 'China', dial_code: '+86', code: 'CN' },
  {tr_code: 'ChristmasIsland', name: 'Christmas Island', dial_code: '+61', code: 'CX' },
  {tr_code: 'CocosIslands', name: 'Cocos (Keeling) Islands', dial_code: '+61', code: 'CC' },
  {tr_code: 'Colombia', name: 'Colombia', dial_code: '+57', code: 'CO' },
  {tr_code: 'Comoros', name: 'Comoros', dial_code: '+269', code: 'KM' },
  {tr_code: 'Congo', name: 'Congo', dial_code: '+242', code: 'CG' },
  {tr_code: 'CongoTheDemocraticRepublicoftheCongo', name: 'Congo, The Democratic Republic of the Congo', dial_code: '+243', code: 'CD' },
  {tr_code: 'CookIslands', name: 'Cook Islands', dial_code: '+682', code: 'CK' },
  {tr_code: 'CostaRica', name: 'Costa Rica', dial_code: '+506', code: 'CR' },
  {tr_code: 'CotedIvoire', name: 'Cote d\'Ivoire', dial_code: '+225', code: 'CI' },
  {tr_code: 'Croatia', name: 'Croatia', dial_code: '+385', code: 'HR' },
  {tr_code: 'Cuba', name: 'Cuba', dial_code: '+53', code: 'CU' },
  {tr_code: 'Cyprus', name: 'Cyprus', dial_code: '+357', code: 'CY' },
  {tr_code: 'CzechRepublic', name: 'Czech Republic', dial_code: '+420', code: 'CZ' },
  {tr_code: 'Denmark', name: 'Denmark', dial_code: '+45', code: 'DK' },
  {tr_code: 'Djibouti', name: 'Djibouti', dial_code: '+253', code: 'DJ' },
  {tr_code: 'Dominica', name: 'Dominica', dial_code: '+1767', code: 'DM' },
  {tr_code: 'DominicanRepublic', name: 'Dominican Republic', dial_code: '+1849', code: 'DO' },
  {tr_code: 'Ecuador', name: 'Ecuador', dial_code: '+593', code: 'EC' },
  {tr_code: 'Egypt', name: 'Egypt', dial_code: '+20', code: 'EG' },
  {tr_code: 'ElSalvador', name: 'El Salvador', dial_code: '+503', code: 'SV' },
  {tr_code: 'EquatorialGuinea', name: 'Equatorial Guinea', dial_code: '+240', code: 'GQ' },
  {tr_code: 'Eritrea', name: 'Eritrea', dial_code: '+291', code: 'ER' },
  {tr_code: 'Estonia', name: 'Estonia', dial_code: '+372', code: 'EE' },
  {tr_code: 'Ethiopia', name: 'Ethiopia', dial_code: '+251', code: 'ET' },
  {tr_code: 'FalklandIslands', name: 'Falkland Islands (Malvinas)', dial_code: '+500', code: 'FK' },
  {tr_code: 'FaroeIslands', name: 'Faroe Islands', dial_code: '+298', code: 'FO' },
  {tr_code: 'Fiji', name: 'Fiji', dial_code: '+679', code: 'FJ' },
  {tr_code: 'Finland', name: 'Finland', dial_code: '+358', code: 'FI' },
  {tr_code: 'France', name: 'France', dial_code: '+33', code: 'FR' },
  {tr_code: 'FrenchGuiana', name: 'French Guiana', dial_code: '+594', code: 'GF' },
  {tr_code: 'FrenchPolynesia', name: 'French Polynesia', dial_code: '+689', code: 'PF' },
  {tr_code: 'Gabon', name: 'Gabon', dial_code: '+241', code: 'GA' },
  {tr_code: 'Gambia', name: 'Gambia', dial_code: '+220', code: 'GM' },
  {tr_code: 'Georgia', name: 'Georgia', dial_code: '+995', code: 'GE' },
  {tr_code: 'Germany', name: 'Germany', dial_code: '+49', code: 'DE' },
  {tr_code: 'Ghana', name: 'Ghana', dial_code: '+233', code: 'GH' },
  {tr_code: 'Gibraltar', name: 'Gibraltar', dial_code: '+350', code: 'GI' },
  {tr_code: 'Greece', name: 'Greece', dial_code: '+30', code: 'GR' },
  {tr_code: 'Greenland', name: 'Greenland', dial_code: '+299', code: 'GL' },
  {tr_code: 'Grenada', name: 'Grenada', dial_code: '+1473', code: 'GD' },
  {tr_code: 'Guadeloupe', name: 'Guadeloupe', dial_code: '+590', code: 'GP' },
  {tr_code: 'Guam', name: 'Guam', dial_code: '+1671', code: 'GU' },
  {tr_code: 'Guatemala', name: 'Guatemala', dial_code: '+502', code: 'GT' },
  {tr_code: 'Guernsey', name: 'Guernsey', dial_code: '+44', code: 'GG' },
  {tr_code: 'Guinea', name: 'Guinea', dial_code: '+224', code: 'GN' },
  {tr_code: 'Guinea-Bissau', name: 'Guinea-Bissau', dial_code: '+245', code: 'GW' },
  {tr_code: 'Guyana', name: 'Guyana', dial_code: '+592', code: 'GY' },
  {tr_code: 'Haiti', name: 'Haiti', dial_code: '+509', code: 'HT' },
  {tr_code: 'HolySee', name: 'Holy See (Vatican City State)', dial_code: '+379', code: 'VA' },
  {tr_code: 'Honduras', name: 'Honduras', dial_code: '+504', code: 'HN' },
  {tr_code: 'HongKong', name: 'Hong Kong', dial_code: '+852', code: 'HK' },
  {tr_code: 'Hungary', name: 'Hungary', dial_code: '+36', code: 'HU' },
  {tr_code: 'Iceland', name: 'Iceland', dial_code: '+354', code: 'IS' },
  {tr_code: 'India', name: 'India', dial_code: '+91', code: 'IN' },
  {tr_code: 'Indonesia', name: 'Indonesia', dial_code: '+62', code: 'ID' },
  {tr_code: 'IranIslamicRepublicofPersianGulf', name: 'Iran, Islamic Republic of Persian Gulf', dial_code: '+98', code: 'IR' },
  {tr_code: 'Iraq', name: 'Iraq', dial_code: '+964', code: 'IQ' },
  {tr_code: 'Ireland', name: 'Ireland', dial_code: '+353', code: 'IE' },
  {tr_code: 'IsleofMan', name: 'Isle of Man', dial_code: '+44', code: 'IM' },
  {tr_code: 'Israel', name: 'Israel', dial_code: '+972', code: 'IL' },
  {tr_code: 'Italy', name: 'Italy', dial_code: '+39', code: 'IT' },
  {tr_code: 'Jamaica', name: 'Jamaica', dial_code: '+1876', code: 'JM' },
  {tr_code: 'Japan', name: 'Japan', dial_code: '+81', code: 'JP' },
  {tr_code: 'Jersey', name: 'Jersey', dial_code: '+44', code: 'JE' },
  {tr_code: 'Jordan', name: 'Jordan', dial_code: '+962', code: 'JO' },
  {tr_code: 'Kazakhstan', name: 'Kazakhstan', dial_code: '+7', code: 'KZ' },
  {tr_code: 'Kenya', name: 'Kenya', dial_code: '+254', code: 'KE' },
  {tr_code: 'Kiribati', name: 'Kiribati', dial_code: '+686', code: 'KI' },
  {tr_code: 'KoreaDemocraticPeoplesRepublicofKorea', name: 'Korea, Democratic People\'s Republic of Korea', dial_code: '+850', code: 'KP' },
  {tr_code: 'KoreaRepublicofSouthKorea', name: 'Korea, Republic of South Korea', dial_code: '+82', code: 'KR' },
  {tr_code: 'Kuwait', name: 'Kuwait', dial_code: '+965', code: 'KW' },
  {tr_code: 'Kyrgyzstan', name: 'Kyrgyzstan', dial_code: '+996', code: 'KG' },
  {tr_code: 'Laos', name: 'Laos', dial_code: '+856', code: 'LA' },
  {tr_code: 'Latvia', name: 'Latvia', dial_code: '+371', code: 'LV' },
  {tr_code: 'Lebanon', name: 'Lebanon', dial_code: '+961', code: 'LB' },
  {tr_code: 'Lesotho', name: 'Lesotho', dial_code: '+266', code: 'LS' },
  {tr_code: 'Liberia', name: 'Liberia', dial_code: '+231', code: 'LR' },
  {tr_code: 'LibyanArabJamahiriya', name: 'Libyan Arab Jamahiriya', dial_code: '+218', code: 'LY' },
  {tr_code: 'Liechtenstein', name: 'Liechtenstein', dial_code: '+423', code: 'LI' },
  {tr_code: 'Lithuania', name: 'Lithuania', dial_code: '+370', code: 'LT' },
  {tr_code: 'Luxembourg', name: 'Luxembourg', dial_code: '+352', code: 'LU' },
  {tr_code: 'Macao', name: 'Macao', dial_code: '+853', code: 'MO' },
  {tr_code: 'Macedonia', name: 'Macedonia', dial_code: '+389', code: 'MK' },
  {tr_code: 'Madagascar', name: 'Madagascar', dial_code: '+261', code: 'MG' },
  {tr_code: 'Malawi', name: 'Malawi', dial_code: '+265', code: 'MW' },
  {tr_code: 'Malaysia', name: 'Malaysia', dial_code: '+60', code: 'MY' },
  {tr_code: 'Maldives', name: 'Maldives', dial_code: '+960', code: 'MV' },
  {tr_code: 'Mali', name: 'Mali', dial_code: '+223', code: 'ML' },
  {tr_code: 'Malta', name: 'Malta', dial_code: '+356', code: 'MT' },
  {tr_code: 'MarshallIslands', name: 'Marshall Islands', dial_code: '+692', code: 'MH' },
  {tr_code: 'Martinique', name: 'Martinique', dial_code: '+596', code: 'MQ' },
  {tr_code: 'Mauritania', name: 'Mauritania', dial_code: '+222', code: 'MR' },
  {tr_code: 'Mauritius', name: 'Mauritius', dial_code: '+230', code: 'MU' },
  {tr_code: 'Mayotte', name: 'Mayotte', dial_code: '+262', code: 'YT' },
  {tr_code: 'Mexico', name: 'Mexico', dial_code: '+52', code: 'MX' },
  {tr_code: 'MicronesiaFederatedStatesofMicronesia', name: 'Micronesia, Federated States of Micronesia', dial_code: '+691', code: 'FM' },
  {tr_code: 'Moldova', name: 'Moldova', dial_code: '+373', code: 'MD' },
  {tr_code: 'Monaco', name: 'Monaco', dial_code: '+377', code: 'MC' },
  {tr_code: 'Mongolia', name: 'Mongolia', dial_code: '+976', code: 'MN' },
  {tr_code: 'Montenegro', name: 'Montenegro', dial_code: '+382', code: 'ME' },
  {tr_code: 'Montserrat', name: 'Montserrat', dial_code: '+1664', code: 'MS' },
  {tr_code: 'Morocco', name: 'Morocco', dial_code: '+212', code: 'MA' },
  {tr_code: 'Mozambique', name: 'Mozambique', dial_code: '+258', code: 'MZ' },
  {tr_code: 'Myanmar', name: 'Myanmar', dial_code: '+95', code: 'MM' },
  {tr_code: 'Namibia', name: 'Namibia', dial_code: '+264', code: 'NA' },
  {tr_code: 'Nauru', name: 'Nauru', dial_code: '+674', code: 'NR' },
  {tr_code: 'Nepal', name: 'Nepal', dial_code: '+977', code: 'NP' },
  {tr_code: 'Netherlands', name: 'Netherlands', dial_code: '+31', code: 'NL' },
  {tr_code: 'NetherlandsAntilles', name: 'Netherlands Antilles', dial_code: '+599', code: 'AN' },
  {tr_code: 'NewCaledonia', name: 'New Caledonia', dial_code: '+687', code: 'NC' },
  {tr_code: 'NewZealand', name: 'New Zealand', dial_code: '+64', code: 'NZ' },
  {tr_code: 'Nicaragua', name: 'Nicaragua', dial_code: '+505', code: 'NI' },
  {tr_code: 'Niger', name: 'Niger', dial_code: '+227', code: 'NE' },
  {tr_code: 'Nigeria', name: 'Nigeria', dial_code: '+234', code: 'NG' },
  {tr_code: 'Niue', name: 'Niue', dial_code: '+683', code: 'NU' },
  {tr_code: 'NorfolkIsland', name: 'Norfolk Island', dial_code: '+672', code: 'NF' },
  {tr_code: 'NorthernMarianaIslands', name: 'Northern Mariana Islands', dial_code: '+1670', code: 'MP' },
  {tr_code: 'Norway', name: 'Norway', dial_code: '+47', code: 'NO' },
  {tr_code: 'Oman', name: 'Oman', dial_code: '+968', code: 'OM' },
  {tr_code: 'Pakistan', name: 'Pakistan', dial_code: '+92', code: 'PK' },
  {tr_code: 'Palau', name: 'Palau', dial_code: '+680', code: 'PW' },
  {tr_code: 'PalestinianTerritoryOccupied', name: 'Palestinian Territory, Occupied', dial_code: '+970', code: 'PS' },
  {tr_code: 'Panama', name: 'Panama', dial_code: '+507', code: 'PA' },
  {tr_code: 'PapuaNewGuinea', name: 'Papua New Guinea', dial_code: '+675', code: 'PG' },
  {tr_code: 'Paraguay', name: 'Paraguay', dial_code: '+595', code: 'PY' },
  {tr_code: 'Peru', name: 'Peru', dial_code: '+51', code: 'PE' },
  {tr_code: 'Philippines', name: 'Philippines', dial_code: '+63', code: 'PH' },
  {tr_code: 'Pitcairn', name: 'Pitcairn', dial_code: '+64', code: 'PN' },
  {tr_code: 'Poland', name: 'Poland', dial_code: '+48', code: 'PL' },
  {tr_code: 'Portugal', name: 'Portugal', dial_code: '+351', code: 'PT' },
  {tr_code: 'PuertoRico', name: 'Puerto Rico', dial_code: '+1939', code: 'PR' },
  {tr_code: 'Qatar', name: 'Qatar', dial_code: '+974', code: 'QA' },
  {tr_code: 'Romania', name: 'Romania', dial_code: '+40', code: 'RO' },
  {tr_code: 'Russia', name: 'Russia', dial_code: '+7', code: 'RU' },
  {tr_code: 'Rwanda', name: 'Rwanda', dial_code: '+250', code: 'RW' },
  {tr_code: 'Reunion', name: 'Reunion', dial_code: '+262', code: 'RE' },
  {tr_code: 'SaintBarthelemy', name: 'Saint Barthelemy', dial_code: '+590', code: 'BL' },
  {tr_code: 'SaintHelenaAscensionandTristanDaCunha', name: 'Saint Helena, Ascension and Tristan Da Cunha', dial_code: '+290', code: 'SH' },
  {tr_code: 'SaintKittsandNevis', name: 'Saint Kitts and Nevis', dial_code: '+1869', code: 'KN' },
  {tr_code: 'SaintLucia', name: 'Saint Lucia', dial_code: '+1758', code: 'LC' },
  {tr_code: 'SaintMartin', name: 'Saint Martin', dial_code: '+590', code: 'MF' },
  {tr_code: 'SaintPierreandMiquelon', name: 'Saint Pierre and Miquelon', dial_code: '+508', code: 'PM' },
  {tr_code: 'SaintVincentandtheGrenadines', name: 'Saint Vincent and the Grenadines', dial_code: '+1784', code: 'VC' },
  {tr_code: 'Samoa', name: 'Samoa', dial_code: '+685', code: 'WS' },
  {tr_code: 'SanMarino', name: 'San Marino', dial_code: '+378', code: 'SM' },
  {tr_code: 'SaoTomeandPrincipe', name: 'Sao Tome and Principe', dial_code: '+239', code: 'ST' },
  {tr_code: 'SaudiArabia', name: 'Saudi Arabia', dial_code: '+966', code: 'SA' },
  {tr_code: 'Senegal', name: 'Senegal', dial_code: '+221', code: 'SN' },
  {tr_code: 'Serbia', name: 'Serbia', dial_code: '+381', code: 'SRB' },
  {tr_code: 'Seychelles', name: 'Seychelles', dial_code: '+248', code: 'SC' },
  {tr_code: 'SierraLeone', name: 'Sierra Leone', dial_code: '+232', code: 'SL' },
  {tr_code: 'Singapore', name: 'Singapore', dial_code: '+65', code: 'SG' },
  {tr_code: 'Slovakia', name: 'Slovakia', dial_code: '+421', code: 'SK' },
  {tr_code: 'Slovenia', name: 'Slovenia', dial_code: '+386', code: 'SI' },
  {tr_code: 'SolomonIslands', name: 'Solomon Islands', dial_code: '+677', code: 'SB' },
  {tr_code: 'Somalia', name: 'Somalia', dial_code: '+252', code: 'SO' },
  {tr_code: 'SouthAfrica', name: 'South Africa', dial_code: '+27', code: 'ZA' },
  {tr_code: 'SouthSudan', name: 'South Sudan', dial_code: '+211', code: 'SS' },
  {tr_code: 'SouthGeorgiaandtheSouthSandwichIslands', name: 'South Georgia and the South Sandwich Islands', dial_code: '+500', code: 'GS' },
  {tr_code: 'Spain', name: 'Spain', dial_code: '+34', code: 'ES' },
  {tr_code: 'SriLanka', name: 'Sri Lanka', dial_code: '+94', code: 'LK' },
  {tr_code: 'Sudan', name: 'Sudan', dial_code: '+249', code: 'SD' },
  {tr_code: 'Suriname', name: 'Suriname', dial_code: '+597', code: 'SR' },
  {tr_code: 'SvalbardandJanMayen', name: 'Svalbard and Jan Mayen', dial_code: '+47', code: 'SJ' },
  {tr_code: 'Swaziland', name: 'Swaziland', dial_code: '+268', code: 'SZ' },
  {tr_code: 'Sweden', name: 'Sweden', dial_code: '+46', code: 'SE' },
  {tr_code: 'Switzerland', name: 'Switzerland', dial_code: '+41', code: 'CH' },
  {tr_code: 'SyrianArabRepublic', name: 'Syrian Arab Republic', dial_code: '+963', code: 'SY' },
  {tr_code: 'Taiwan', name: 'Taiwan', dial_code: '+886', code: 'TW' },
  {tr_code: 'Tajikistan', name: 'Tajikistan', dial_code: '+992', code: 'TJ' },
  {tr_code: 'TanzaniaUnitedRepublicofTanzania', name: 'Tanzania, United Republic of Tanzania', dial_code: '+255', code: 'TZ' },
  {tr_code: 'Thailand', name: 'Thailand', dial_code: '+66', code: 'TH' },
  {tr_code: 'Timor-Leste', name: 'Timor-Leste', dial_code: '+670', code: 'TL' },
  {tr_code: 'Togo', name: 'Togo', dial_code: '+228', code: 'TG' },
  {tr_code: 'Tokelau', name: 'Tokelau', dial_code: '+690', code: 'TK' },
  {tr_code: 'Tonga', name: 'Tonga', dial_code: '+676', code: 'TO' },
  {tr_code: 'TrinidadandTobago', name: 'Trinidad and Tobago', dial_code: '+1868', code: 'TT' },
  {tr_code: 'Tunisia', name: 'Tunisia', dial_code: '+216', code: 'TN' },
  {tr_code: 'Turkey', name: 'Turkey', dial_code: '+90', code: 'TR' },
  {tr_code: 'Turkmenistan', name: 'Turkmenistan', dial_code: '+993', code: 'TM' },
  {tr_code: 'TurksandCaicosIslands', name: 'Turks and Caicos Islands', dial_code: '+1649', code: 'TC' },
  {tr_code: 'Tuvalu', name: 'Tuvalu', dial_code: '+688', code: 'TV' },
  {tr_code: 'Uganda', name: 'Uganda', dial_code: '+256', code: 'UG' },
  {tr_code: 'Ukraine', name: 'Ukraine', dial_code: '+380', code: 'UA' },
  {tr_code: 'UnitedArabEmirates', name: 'United Arab Emirates', dial_code: '+971', code: 'AE' },
  {tr_code: 'UnitedKingdom', name: 'United Kingdom', dial_code: '+44', code: 'GB' },
  {tr_code: 'UnitedStates', name: 'United States', dial_code: '+1', code: 'US' },
  {tr_code: 'Uruguay', name: 'Uruguay', dial_code: '+598', code: 'UY' },
  {tr_code: 'Uzbekistan', name: 'Uzbekistan', dial_code: '+998', code: 'UZ' },
  {tr_code: 'Vanuatu', name: 'Vanuatu', dial_code: '+678', code: 'VU' },
  {tr_code: 'VenezuelaBolivarianRepublicofVenezuela', name: 'Venezuela, Bolivarian Republic of Venezuela', dial_code: '+58', code: 'VE' },
  {tr_code: 'Vietnam', name: 'Vietnam', dial_code: '+84', code: 'VN' },
  {tr_code: 'VirginIslandsBritish', name: 'Virgin Islands, British', dial_code: '+1284', code: 'VG' },
  {tr_code: 'VirginIslandsU.S.', name: 'Virgin Islands, U.S.', dial_code: '+1340', code: 'VI' },
  {tr_code: 'WallisandFutuna', name: 'Wallis and Futuna', dial_code: '+681', code: 'WF' },
  {tr_code: 'Yemen', name: 'Yemen', dial_code: '+967', code: 'YE' },
  {tr_code: 'Zambia', name: 'Zambia', dial_code: '+260', code: 'ZM' },
  {tr_code: 'Zimbabwe', name: 'Zimbabwe', dial_code: '+263', code: 'ZW' }];
